apiVersion: apps/v1
kind: Deployment
metadata:
  name: riu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riu
  template:
    metadata:
      labels:
        app: riu
    spec:
      containers:
      - image: okteto.dev/riu:latest
        name: riu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d12504e8-181c-4df8-a3fc-e4ddeffd5eab"
        - name: Vless_Path
          value: "/ghiuy45lkjrty"
        - name: Vmess_UUID
          value: "d12504e8-181c-4df8-a3fc-e4ddeffd5eab"
        - name: Vmess_Path
          value: "/lkjwe34qwdfgh76"
        - name: Share_Path
          value: "/v2link"
